services:
  postgres:
    image: postgres:16
    container_name: civicpulse-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: civicpulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - civicpulse_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: civicpulse-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  civicpulse_pgdata:
